server:
  port: 8090

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-bills
          uri: lb://ms-bills
          predicates:
            - Path=/api/v1/**
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      client:
        provider:
          api-gateway-service:
            issuer-uri: http://localhost:8080/realms/parcial-andrea-diaz
        registration:
          api-gateway-service:
            provider: api-gateway-service
            client-id: gateway-client
            client-secret: MAd0ZfC6UtW47vHtuIebmKPbyOCGqWWH
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak

#Eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway